---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cephMigration
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  rollback:
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    global:
      nameOverride: *app

    controllers:
      cephMigration:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ubuntu
              tag: latest
              pullPolicy: Always
            command: [ "dumb-init", "/bin/bash", "-c" ]
            args: [ apt-get update && apt-get install -y gdisk smartmontools hdparm sysstat iperf3 lvm2 python3 && echo "Go to sleep now!" && sleep infinity ]
            env:
              TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}-no-backup
        globalMounts:
        - subPath: "data"
          path: "/home/cephMigration"
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
        - subPath: "tmp"
          path: "/tmp"
          readOnly: false
      # CephFS folder mounts
      media:
        enabled: true
        existingClaim: ceph-filesystem-${APP}-media
        advancedMounts:
          cephMigration:
            app:
            - path: /mnt/unionfs/Media

