---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../components/cephfs-mounts/media-folder.yaml
- ./pvc.yaml
- ./helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
- pairs:
    app.kubernetes.io/name: cephMigration
    app.kubernetes.io/instance: cephMigration
