---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_CLAIM}-no-backup
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 250G
  storageClassName: ${VOLSYNC_STORAGECLASS}
