---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx
  namespace: &namespace home-automation
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: *app
    namespace: *namespace
  # components:
  #   # - ../../../../components/gatus/guarded
  #   - ../../../../components/volsync
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/home-automation/emqx/app
  postBuild:
    substituteFrom:
    - name: cluster-secrets
      kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
      GATUS_PATH: /web/index.html
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_STORAGECLASS: ceph-blockpool-nvme
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emqx-cluster
  namespace: &namespace home-automation
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
  - name: emqx
    namespace: home-automation
  healthCheckExprs:
  - apiVersion: apps.emqx.io/v2beta1
    kind: EMQX
    failed: status.conditions.filter(e, e.type == 'Available').all(e, e.status == 'False')
    current: status.conditions.filter(e, e.type == 'Available').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/home-automation/emqx/cluster
  postBuild:
    substituteFrom:
    - name: cluster-secrets
      kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
      GATUS_PATH: /web/index.html
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_STORAGECLASS: ceph-blockpool-nvme
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
