---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../components/cephfs-mounts/backup.yaml
- ../../../../components/cephfs-mounts/downloads-folder.yaml
- ../../../../components/cephfs-mounts/movies-folder.yaml
- ../../../../components/cephfs-mounts/music-folder.yaml
- ../../../../components/cephfs-mounts/tv-folder.yaml
- ../../../../components/cephfs-mounts/media-folder.yaml
- ./rbac.yaml
- ./talos-serviceaccount.yaml
- ./secret.sops.yaml
- ./pvc.yaml
- ./helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
- pairs:
    app.kubernetes.io/name: coder
    app.kubernetes.io/instance: coder
