apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
type: Opaque
stringData:
    ssh-privkey: ENC[AES256_GCM,data:wWjEVwmaeezrsJ01ZH6wj2biZwO0ZNAm/lQ9qJygw1MihTVbhcWbpGm9OjVR5/j07mrv9G8gXB5ms5XLZTymc+IvDAsC5KBB5BwXgNdAF6VIK7MCIFsADbI75/nkd/RDKhIBPLMM6pthk8gD8aZ84nGH1gCLgw9NKCRNzq8XkyL4UBnyLE7bBSb+UNFrOQ6bgSXyRx4gZtLxuyEl4Q0wromI3T2caesfg0tk0HLZsjH72WkQuQkv59ddPPEnXdnIdPg9dgg9mOT/fPh/oZB/zso5zTpcjxRcyQ3vVJNy5Pl+ghsZsr0Rr/7aDkg2DDths7YZeXaZBapFTu4McOUp/dI3nxMVivbk1eMZwl8zbF1f3mIHT7RojjwdLWLoku1OKj+uUeIYGh/zuFG5UNvQKcopPQ2KpemEL2mDmYPWs6LXrrld1Ox6vMP0UB7XiXqnvOKW5ven6vCi1E5z6MZMcGV2ZZhKLM0g4bRfT7y1P6rOrvcyOWrDFARaBa11DlcEmfy0lLpyKJNjxW4=,iv:b/j90J7hS9l9+4/UDisBvPvhhYA3lgVUz8+yKPG+XTU=,tag:F+47p4CvAUWAW+vevXAdWg==,type:str]
    ssh-pubkey: ENC[AES256_GCM,data:NHtwhbNzbwJUhhhCYctN79G4QYjJE5aYllDPpZSdfuDtC4ZxB/tGIuBXjVtBK6LBilrZHN+z0GKHfi8xGLrmDbPq4S6NQpZAPc6icSphJRwUtwpn/XMt8iKTE5Khy6Ec,iv:9+Z531FsW+mtntrMWYofF8Vyyf7H6AZCeqtAEBmR8B0=,tag:XDSMFmfwGAJXj/s4TP5TnQ==,type:str]
    age.agekey: ENC[AES256_GCM,data:AHubfBcGsSAqkT9DDPVFP75TY+KaQrruDwxfVNVkTIA+Pfi6wTk5HeQVT9a0OM6mvL90ATMFHEvOhKgOexVdo6Ow+CgA6SRA6BY=,iv:BnhbYMl7eSMw7ii4nTO5qGGTMjadrMTOtSRD0XFagtQ=,tag:4Ea7WYdnb1pUqkojk8i9RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWWlZMEY0V2FmeExpTWt1
            QmlWeGJGV1NrMkFFak0rWGwwQ3dDM0plQTAwCmNhMEhLZFBzaHZXdGF3ampQOC8y
            Y3UxT0xhdWt5eDNuYmZ0TVVvdGt0MzgKLS0tIHkwcXUwV2VnRno2NjZXbnhmUUt0
            VHZEQ1Q1cmxLeG5QMnNtMHN4N0tCVFEKFCe4k7wVLWjoyqxdkusWNd/Bb6dL5DWg
            o8NKEJtoOos9IB+twAdEwyhHOneJGBjPjdEa1DGQL0YOcCsGsFguJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T16:42:06Z"
    mac: ENC[AES256_GCM,data:yFMAdCL/dHf674u8LDgw3agLDRUA/I62fsWGGZZIP9+xz7VH+Pa6bD17acziHRcCE5MS7Ka25tqmelJFBYbcfo5qgP/HBUA4SnMZuzrIlJ4P5DH2aTK+McRoRgY+wOi3h/H5k9GTFgvWHU+hv0PBSonw+oiek0PKlXp5a93zsLs=,iv:QQA+WJxhJ1WRw+iQAc5y0QTb6RM9p+38r/rzy2mqx8s=,tag:7g1uTRprtIMvv8jcMSDMFg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
