apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
type: Opaque
stringData:
    ssh-privkey: ENC[AES256_GCM,data:n50ZZwlTCtsQpbJFlbu6GixhOMerQygdGb9IRq5dk3P6tkx+v+WnjCbMc55V0cEig98Sa9zw/tnXVx4hNp38dAcX2HQup/2f3m+U126WYVlRm8qEPjGLOkoLDbJTekKUGpn0+eyWizb5FWGqFp0E3t79jAtN+Melf1iE4BMxi6pqLRL4abZnMBMvsKa0kxuxB6PZ4ytE4l9d2HWkKovMlXrIs3Q3oc4lG3Dmi5wcXKXXkQu4fm2MMIlYibPA2Sy3ley1N8sS2yzHe4ebm17nqUxlWdKEIcQQRw0dW8Y1WHNua2xnIhA6EH6OsbzVmcUf+Vti9xv6+G4w8Rmnp/RmbJllCFPvQMWG0iY2UdIbcxRfhJlJ2jgVqfBIwqk1mdlK46QVUqoWiLDDX8O36o8aPhmx+mGwDg6Qap7fRyK7bu89Z10pGDgCry3ALGdd52Y93j+t/0R5ft0u1QgVwenm+sQZM5PgW12eJSnHj4mGfOK7+LZQXj0wuSd9sYA1zOr6AHhB3k5/nJD/PFtR7MV+,iv:77pEVnZKkIPqj55/5zhUe8Zgu1rbZl6k3K2e0AEeaWk=,tag:TuVwzar+0j+Uh9DbJW0vwA==,type:str]
    ssh-pubkey: ENC[AES256_GCM,data:NHtwhbNzbwJUhhhCYctN79G4QYjJE5aYllDPpZSdfuDtC4ZxB/tGIuBXjVtBK6LBilrZHN+z0GKHfi8xGLrmDbPq4S6NQpZAPc6icSphJRwUtwpn/XMt8iKTE5Khy6Ec,iv:9+Z531FsW+mtntrMWYofF8Vyyf7H6AZCeqtAEBmR8B0=,tag:XDSMFmfwGAJXj/s4TP5TnQ==,type:str]
    age.agekey: ENC[AES256_GCM,data:AHubfBcGsSAqkT9DDPVFP75TY+KaQrruDwxfVNVkTIA+Pfi6wTk5HeQVT9a0OM6mvL90ATMFHEvOhKgOexVdo6Ow+CgA6SRA6BY=,iv:BnhbYMl7eSMw7ii4nTO5qGGTMjadrMTOtSRD0XFagtQ=,tag:4Ea7WYdnb1pUqkojk8i9RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWWlZMEY0V2FmeExpTWt1
            QmlWeGJGV1NrMkFFak0rWGwwQ3dDM0plQTAwCmNhMEhLZFBzaHZXdGF3ampQOC8y
            Y3UxT0xhdWt5eDNuYmZ0TVVvdGt0MzgKLS0tIHkwcXUwV2VnRno2NjZXbnhmUUt0
            VHZEQ1Q1cmxLeG5QMnNtMHN4N0tCVFEKFCe4k7wVLWjoyqxdkusWNd/Bb6dL5DWg
            o8NKEJtoOos9IB+twAdEwyhHOneJGBjPjdEa1DGQL0YOcCsGsFguJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T16:48:28Z"
    mac: ENC[AES256_GCM,data:cjnahvvAZDRmw8WI3qC00fu7S6WUeFXFWDI9I2GPpWsh2zi0IMcK5+rRO+ZCJKnGJdIMofF5dXh4h/HLB5rwoa9ICmLdBiEOVk+zXFa6NSgNDJE3UmCbfVM2tPjiO9UtKpZDaMHNzkvgEpBXIi6p23eNXUpDDq4MlaJfOSLiwIs=,iv:vkC3SCPh8F5f3LNSbE7+ZlkwqVzz4dz8XyXccilQ2yo=,tag:Uh2U5tEOU9Y+oB1XnkjHrw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
