apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:cmbHddAXTOD7w6+08aIoWdrqTeCoZaY8OcXP8sHv2+kOFGUontUmuReo0y588f4Mi6vgcA+6vbPMHCn2tEUj0UFsrtQf6+v6P8+WHNbPjSPU8WMA2DZ8TQ3zDhCzY5Eu/fccLugHKQ+RT0HOB2DS4FHavxtNczpSnxQPlq/k0f2m19yusT9wVDsc1OGw56qY+TO6Mbp4FI/V16ybJD2YhoZjF1abaZOn17myFY0ONydMQMbJlaxHfdBpVMI+q7BDBKNxdlkVTGNO4byEQ3dYCkiX4A0ncz5j4ZCJUx2UC9cj9ojF+Eb2GYwpq/9CgFN91HCkpiLFt4hGu+ptBokEIlQK193IuHxn3rx1vOf2OMlCHMwfT/Ch+q3hNO4mmL2xvGnztzJXqT11LFMrwTCEa1uxgHUq930kgMYwqt/1VtdPV+Kej3iWP8491jTyzFfihoiHTFSOlrn2qTCixASschcMS8W5SClZAVM08RxhKY7bfSL6QxUHgnXGeJJqPqI9nPyYA21EekiWIfVXJFL9lAI/6j1qezCpL04=,iv:xTMCR8qjrLaQQBMkbeTc+2TxULb2ZujhvK2EzPV8LZI=,tag:T64xiOZ05XjNkqasya/z3w==,type:comment]
    ssh-privkey: ENC[AES256_GCM,data:9AkUYBUALH4Z/prwMWrdSewDl1Cvi+sKFRTRpU2rEcPiyyEyc89y8QeYYtajnm2LMiUuYHmH/FFbLeR+WUX6q+7X6GWtkKt62JfNTMt67cP3U4rj5AGSkmX1PNiHgDAQy4tz7iD3NrGmd19Zo1aT7wiLi5FFxUR2MYuhOq0tamYF4XhX2fKQGlTXoyfWxRNbT/zZFbMQSlKDc1qUkZW8yufiH3QWwVvvhESobyHDbl4j+5MO8bVNPSIspb0Fy5fOxLQuaLh8UaOEBgZ9S8M/KHj/hvfra/rWKLsiEa34Ex7VG8GLPs5/h3e/bfC/faPqwN2TxezVcBKegn6WKI/TpPU45e/DedbdZIi7EYD9slOX8Eu/Q/ITEhR4mE/n1q4sSLqmdJbkfQVu4vntpC5pbVh0CUoCEkwz+Bdlde7zJTrrY/uiDZK+HI0ZU+mTQwY01Coxyxr70dpvFY91pEW2hDjzHl4901fgvh7iYu4Jz1KSa6aOoXimEZhSpgwOCuDbSuz825GU/0HIu6TeP32AjXw=,iv:/6tNq89PMuBYFLFnf0nCCnriXeO/WXBvdOJOt7tZGQE=,tag:TGA1kEXc1A1iefl3eFRCkg==,type:str]
    ssh-pubkey: ENC[AES256_GCM,data:NHtwhbNzbwJUhhhCYctN79G4QYjJE5aYllDPpZSdfuDtC4ZxB/tGIuBXjVtBK6LBilrZHN+z0GKHfi8xGLrmDbPq4S6NQpZAPc6icSphJRwUtwpn/XMt8iKTE5Khy6Ec,iv:9+Z531FsW+mtntrMWYofF8Vyyf7H6AZCeqtAEBmR8B0=,tag:XDSMFmfwGAJXj/s4TP5TnQ==,type:str]
    age.agekey: ENC[AES256_GCM,data:AHubfBcGsSAqkT9DDPVFP75TY+KaQrruDwxfVNVkTIA+Pfi6wTk5HeQVT9a0OM6mvL90ATMFHEvOhKgOexVdo6Ow+CgA6SRA6BY=,iv:BnhbYMl7eSMw7ii4nTO5qGGTMjadrMTOtSRD0XFagtQ=,tag:4Ea7WYdnb1pUqkojk8i9RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWWlZMEY0V2FmeExpTWt1
            QmlWeGJGV1NrMkFFak0rWGwwQ3dDM0plQTAwCmNhMEhLZFBzaHZXdGF3ampQOC8y
            Y3UxT0xhdWt5eDNuYmZ0TVVvdGt0MzgKLS0tIHkwcXUwV2VnRno2NjZXbnhmUUt0
            VHZEQ1Q1cmxLeG5QMnNtMHN4N0tCVFEKFCe4k7wVLWjoyqxdkusWNd/Bb6dL5DWg
            o8NKEJtoOos9IB+twAdEwyhHOneJGBjPjdEa1DGQL0YOcCsGsFguJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T14:24:17Z"
    mac: ENC[AES256_GCM,data:4idC43s6jFTb/nmaXvpBud4Q+DMopze1SgsBzz3khN4mi2UhElyIJ2lHRYdMOL/+7ly2GncfKiXwgj0qnr624QHR0fum2fyZigLycQZOvDkrA8MjiCuddoqHij4Cajbku1aa1tyc5Mh5GzLfQPk5QRjvh3vNPZwW2ZJA5QvdXgM=,iv:ztKPJ/xENnDFYBXrQdHLAITE9kjVltZx+Zy53p3/mlQ=,tag:PdNUEkIa8ZDaLPbEtFbusw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
