---
creation_rules:
- path_regex: talos/.*\.sops\.ya?ml
  mac_only_encrypted: true
  age: "age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa"
- path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
  encrypted_regex: "^(data|stringData)$"
  mac_only_encrypted: true
  age: "age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa"
stores:
  yaml:
    indent: 2
