---
creation_rules:
  # Old cluster path, will remove after converting
  - path_regex: (k8s\/(global|clusters)\/.*\.sops\.ya?ml)|(k8s\/(global|clusters)\/.*\.encrypted)
    encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
    mac_only_encrypted: true
    age: >-
      age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa"
stores:
  yaml:
    indent: 2



# ---
# creation_rules:
#   - path_regex: (k8s\/(global|clusters)\/.*\.sops\.ya?ml)|(k8s\/(global|clusters)\/.*\.encrypted)
#     encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
#     # Personal, Flux
#     age: >-
#       age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
#   # - path_regex: (global|clusters)/.*\.sops\.toml
#   #   key_groups:
#   #   - age:
#   #       - age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
# 