# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ejyfs+d/3WtFjDmh+4ll/XkIk/ze2j2CfcGXYXexvVd4aXxGVat+Qw==,iv:5Ho9d9i9Psguq5rTJkIpSLF809emjCZBcdw55P3jEc4=,tag:BxO4kcZs6gAQu+y1PGiUiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTVRJQ1lZdHJIVjFkU2py
        Z1dJSGlmdEtwaGpCMFprektXQjZYMFh6Mm00CmlYUGt4cGpUL3FxV3UrMWwzOGov
        WDNaOFlFeWE1aVVCcnI1NHJMdkxGVUkKLS0tIERrcnNHclRXMWFZVnR3djRkWU9q
        bHVtNFNYK21PK294VTZwMlVxZmZ2QlEKegX3wwBVr0ug80NXjqUNCXUV4Ii7Cx5J
        gkyCzmYfy2rWS6gHwmED8IhSnefDja+LsBNm89EVqNMm9qS+O7+2Pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T02:32:56Z"
  mac: ENC[AES256_GCM,data:xZQ7G7LfN8KrDUDNbFgpcE/FhBqBZD0kIY953OiQyVm/B0s3Tdf1NiB3GaxapYzw4aAJu9veIgEFcF0eQb+s75CkjKKhKZNJHjbQZDnFluwmFA9tzLXZb1wC/bMHPYqOsIkafE7vQfKLPEqf/0w0zMGfRYT+ZFeEWGsZMH0pGOI=,iv:FYb8IGRhNQwX6EZK/V5qyGG0RaZGcQSkHMcYxxYy8lQ=,tag:NmNsTE17gWQaDQzIgj4mNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
