---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wyoming-whisper
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  rollback:
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      wyoming-whisper:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: rhasspy/wyoming-whisper
              tag: latest
              pullPolicy: IfNotPresent
            args:
            - --model
            - tiny.en
            - --language
            - en
            env:
              WYOMING_WHISPER__INSTANCE_NAME: Wyoming-Whisper
              WYOMING_WHISPER__PORT: &port 10300
              WYOMING_WHISPER__LOG_LEVEL: info
              TZ: ${TZ}
            resources:
              requests:
                memory: "256M"
              limits:
                memory: "8G"

    service:
      app:
        controller: *app
        ports:
          wyoming-whisper:
            port: *port
            protocol: TCP

    persistence:
      data:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}
