---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/cephfs-mounts/backup.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/instance: tautulli
