apiVersion: v1
kind: Secret
metadata:
    name: autopulse-secret
type: Opaque
stringData:
    AUTOPULSE__AUTH__USERNAME: ENC[AES256_GCM,data:QLF8OkyZbZA=,iv:Tq+BGm4ePSRMWowW7gSCyLy2lf5nkL0VmQtbY1VBpFE=,tag:G22NYCnVOcGs9B3G+SUZGw==,type:str]
    AUTOPULSE__AUTH__PASSWORD: ENC[AES256_GCM,data:E0fI6K9gg+m3DQ==,iv:tbY0JrX2Lyj2LGlO3TdT9s5/3zjO1CBIu+Y1KOf5pHY=,tag:GdAeGD1vqj5HFHopzsc4ew==,type:str]
    AUTOPULSE__TARGETS_PLEX_URL: ENC[AES256_GCM,data:mKtzvW2kBLXrh1xB2aRnO2J670VL2BF08aNMrkEaxoH7QqcVAKS0fJeB,iv:ckdOHN5yV4M3Yl+6V5auMQevozcouXwUIwqcL5OCOw0=,tag:uRGZSOoarL+XlZZ7VBKRdA==,type:str]
    AUTOPULSE__TARGETS_PLEX_TOKEN: ENC[AES256_GCM,data:HkjfbgLB+FidamGl8QXS3qtUHgM=,iv:9ND+DMMsjbgieq6TlCESN1/vJk5CK6kQ3B77kVsA/T4=,tag:L9CYzK+hjr+aM+saM6oaQg==,type:str]
    FORCE_USERNAME: ENC[AES256_GCM,data:7ep6N4g5iwY=,iv:g74tQSVW/17RQBqT4ULAB/iS3ZugGA3IofDZcho1518=,tag:nKAAtTLYumnuXkJ4IYy02g==,type:str]
    FORCE_PASSWORD: ENC[AES256_GCM,data:eJT0yk3oUWpfaw==,iv:e7zKr4363DOrl1lREeMH3AWRGAynUeXnLK8sph6tUwI=,tag:FqWmLlH80/ZjzWLAk3QLIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvclVkcWJ1clFKcWlCNi9J
            bGF0ZStRZDhLenA1Q01La1B0SXFXc0lEQkdvCi94YmkxYk9DdGRheDcrU3NXQVR1
            SFY4UndXcE12OWVKSlhIazdYWGFiTEkKLS0tIFhoMlU0ZlpZcE0wMUFKV25ueGxP
            MjVIazkwVWF2UkxiT1pGZ0lYakpOcjAKKocq88Cb7JmM0eTcfzuAiOBUv4Wihyjq
            h4BpWRzN/1wkJM4qMUT4pRCQncidOP0kyaLWZlDsVgjKe3SMMUdTVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T19:38:38Z"
    mac: ENC[AES256_GCM,data:hauoJ8P3Mj396RaNHWdYsUvVw8lYsJDUpchgHUsW3bNFSzBQycNXhSpNuLyTpAYwbBJHyMhWyakKADkZuO3XL1pzWVNcMXTnfmhzKX6WZc7o8y3WefCNZpsrczK+NrK+JmZr8Qst+xVk2fg6RmlMb7s7MV0KwHXjmgxxAvJf6Q0=,iv:D5+Ymai/0s6xeCeG1zd6Xuqnz1RhmCpsEcpxnYmmn8U=,tag:Jg82UNYXo/qA2aAnYwp6gQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
