# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:5TtEbyjcBbu1lpYgPYXlcIeQ5iV163uTVWWOfEkX4045meOHxi2bDw==,iv:JXorAvJHgN9ikwf1itsFtTX6U0fDmQLE1KvC76phKMU=,tag:/vPqlePIotIddZBp/2NV+w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN2xTZVdNQ3UwRTdGdjVq
        K1k4VkRnaHVja3FrdE82b28yUG5BRzcyVVRzClFMc1U3VG1oV3VoVVFzK1IvTWdR
        c3JTSjJzdlRsdy9LeTMzK2hScGF1M0kKLS0tIC9sZHFXenBiQzRyd04zdVZwNW5N
        ZWdrU3MrcmtmU1J3dHlVM3ZsSEdJTnMK89h4CBK7i2rT3X6jDYL+xBBEiWwCVDNs
        6b6/JVse/X2JLPZPe3BxV4ctQYA04GSMnxOptRE10+wYDsYFZChmKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T21:14:11Z"
  mac: ENC[AES256_GCM,data:NSMg3vo9G5XMxBv5tEkf+ZY8E4J3Qz9bJc9sv6wukDRay9ZLdBohw8WsUgj8bAfRIInLPNnfkQ+yQiGLvu1YFa538PCff9001csUpcPvPBV8t7aLhIn9l2zGBXVXsvd/LGZSo+B2F/xIo8Q0nybVwSdJKX4JLFUN91To4HEs414=,iv:K6EkWRztiZuZOD8R1zFaaFgP12/bI59Q4jQONjtel+M=,tag:8JtEvXf9JnkayMhFeWM4iQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
