# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    #ENC[AES256_GCM,data:D5Ae+Uqi9pZo6WtRaS9KiNRAYlp7Gw==,iv:T9lBBmpinWKSj6AS0SciKU7lUwNis9K4kBhEKj1jwrQ=,tag:r/HSWDfmBvJLsrWIc8llMw==,type:comment]
    token: ENC[AES256_GCM,data:MLywvV/NxbY63qPrerysXe+AceCkwNHZPG8n6p7OkQpW+6qlpnWsrw==,iv:QgW/sd7UIq3EUaFqkvJxjapoYcnL+wt5+tSNCJK+PtU=,tag:gaUdeBBJUAQPvaz77ZRV2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMkNBdWRqMmYvU0lMWG9x
            Qm5jZys2aTVvTVpTL1hFZm1OMGZ2VEpacnlJCjVaR1BpZWNXSDF4TGo5cG1IYVJK
            aUF5SU5pTlNiR0tIWHlPUC95eE85YTgKLS0tIE4vT0pKQUUyYUd3WG1YNm5QVmtv
            YWQvSzBKd3FRekNLWG1VVE9iY2ZzaEEKTgcXj42SAsS80NtJdybODn5QRY5JIEkD
            NuTf8jKYKULoPn8fnCALxwuorm8OcqfJysbjMDbaBRx7B086xM6HIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T23:09:37Z"
    mac: ENC[AES256_GCM,data:Tjnr3053L/tMxclJTxTcbNdeDcBsLmq4Bjr+9Odv03N2fjJlt67Y5tjoGYyc/c2CIQBWZrc9VuniBz7Zh/pvl029rgImTSbI0dzsePMIWrTYh7laYkE+XnDA7Tvy4ADSY3Dfv6ChRrDMiiLWiHFAjW27He7SG7/X5UV6UiWpdCw=,iv:9+z6bzGLsSWddU8nz6iPAAoEFMaqRNDo0z78v8nM/Fk=,tag:D2fS1EkYW7RgNYylapi03Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
