# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    labels:
        app.kubernetes.io/name: lldap
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Il0LJw==,iv:Fu8OYqCidmGmNJ0e7WKUXkO+2Kw8dtvriKbsL43tFAs=,tag:6ba1yQ4Dbh+Zu4kTqqlFsg==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:p2bOYpNXp3QWAwkf7x44nA==,iv:AnUn0OKkdIYI+aamRwmkI1K0fNGtjEhzaJixJ37TYUc=,tag:OQBXzGf+og6HDQKRMDuO3g==,type:str]
    #ENC[AES256_GCM,data:i7tyecQgPc+Xtza7V4l3t5r5zJOlSYgnyGB8+z7xXqRFMI4GyOqmQq8eDoEM3XH28cCZR65SbkHlqlG4Gwv/A8ePyynedyY=,iv:KHwHlAM8k0Rm4N5QScv48AAqAhpPkOgQB297WH2aqA4=,tag:xZZCaBOyL3J6Ki9ykUkB0w==,type:comment]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:2JsKAyOEE5lNvw==,iv:9RU3mBHA36IGzVahg1loPq6n6I0xOhKC4YxMu7cV1ss=,tag:Ty+etQFk1mgJRGsy2LcHkQ==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:op2rWS2Z+As=,iv:d32EWgY43vBtaIk0DFdZ+gXbmUMcp7p7Wi7EvfQU13A=,tag:FiN1pEQulqymDp3Qh95iKA==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:TEL57kguS9OeNGfxjTyfUVp5KvU/NZMW,iv:zExqrvdatlBuzDSoU4Y9k/9YbFqRjrcjld0+Y9Ziveg=,tag:QvCKt+1zukYWWYyKhbQ7Ag==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:WpTiipmJoaszXyJsfvVCL8/Am8Vo5/SJKJDQRIR6vrw=,iv:NcYCitsmla8RmEaFC7SMllYSqlWzxWao+3mOjOANLX0=,tag:QKwcjKwcGhfZeLB56v3vMA==,type:str]
    #ENC[AES256_GCM,data:5ekdzU11TCmi8VkcIQDvIDDlLaqSPkMjgQWwYWZbzOboSULA8Xe17c+emquNtiPpIptxXe8TWROkgfu1YuF0xbRHfkyMCkxnyN6eaODGL0P2JoZoRmljDBX9ZOIjwh6aSd2heHn9/RlPSfgDh7ohL9XR,iv:k9u5oPCVzycD7vqYF2YpkZdu6LJWXAiZtIU3FZcMgm8=,tag:lb5RJ2MVYh4Gfnp6XX37Pg==,type:comment]
    #ENC[AES256_GCM,data:e6pIcdOZnZmkj7Wvm6Q=,iv:fKLJ1bdFLlhV438mXNUYbYiTv4c6hi84N7cM+X2sVJc=,tag:rny7YpOeMRwb8bwv2pie1w==,type:comment]
    #ENC[AES256_GCM,data:1niObIhOj+ZI6Nt6DQCC27OM68cJlemE0PEY,iv:tOY/A4uwYEPH99aU9RvKrnwu+TY6wxXT0PQzut45XsY=,tag:4d9AH6X/MQkFxnvVEfSgsw==,type:comment]
    #ENC[AES256_GCM,data:iHs1EKqKUm8Tp3hhqFjg+fIX0FnTcsF3ZxX8Qvv49UV+8YaR80AuD0jzl6eBtOWKeIFXP942mpoR9dQB,iv:UNn07hXW66kJbdhVTCuCoTcoGPpmPkTVRgZBpfOIgFU=,tag:9jsstoD9bzlheQj3OMueiw==,type:comment]
    #ENC[AES256_GCM,data:S3+ddjsAxvcJMgkwa2tisOb35Kc/JaS57w==,iv:b+NLdCHJ4KixebdcHZqYod92huazoki/0hDDqssG2xg=,tag:jtNSNFlXE8CWX8q3p+ZKOg==,type:comment]
    #ENC[AES256_GCM,data:7wYhwgoOdraujeu5iCtbHj8YZFwh/axpDTXdbCQUTIjMcN7NjI+RfbuM7a5x7lPYOcc=,iv:QdaV35bbvQjJuk995x6iYZyTrg3a9oQGgJARM1qZxMM=,tag:E/Ljuod5w4VPFykjtDPf6g==,type:comment]
    #ENC[AES256_GCM,data:j9kgONUUzYFH7MALghe1i3W/ufh8dAiYzRYXHpFMA79ZrkXI,iv:WVyLFXInENRcQwrOWa2y67caHZN137+x25EqEAbuTtQ=,tag:K/NEzsxHRe6ac0YY/sIHQg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3FDeUpXSU5kL1IzYVpS
            U0plaVhrb3pxNXpJNWpuSTgxSVIxMVZVQWdFClRjamh4NG4xZktzalpSekY0NWhq
            eTJWdWJjVCtkOGZYRzRjNk9TUDBxRWcKLS0tIG9WOWNpcFJKeGRkdm9wUk96TXRZ
            Nm52S1FCU0Ewd0lySTBvVjY2cDgwdzgKeDe9ArsX2CkGF50MbaB0D49MAlxBLPkw
            1JctP8aOC2iuOVZLIIuDM1XLg8ckQ0tf1cSJpMfMOv95YewIlIWBFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T15:24:11Z"
    mac: ENC[AES256_GCM,data:c+SvfAvvE1vyl/dtje+Y6xT7ANn0vRm9ZgAToABJA9na2n3USZYLYW2moyWUAHgYJ1E95uA7Ih16CEg7ZiAUIbRasP1W3y+tdxmuJxFeqGRinn+9JZrZLI0bNy5DPYjtgLpITNoY3pmNPb4ez7lkG8/0cT42Abv6fPxW+hpmhM8=,iv:wGnmDQhJ61hUx3/VJige0ov1Z8srX7dhZgOWKWZJz6o=,tag:VGnbL3WKBwYPKlG1sVxuXw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
