---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/cephfs-mounts/4kmovies-folder.yaml
  - ../../../../components/cephfs-mounts/4ktv-folder.yaml
  - ../../../../components/cephfs-mounts/backup.yaml
  - ../../../../components/cephfs-mounts/downloads-folder.yaml
  - ../../../../components/cephfs-mounts/movies-folder.yaml
  - ../../../../components/cephfs-mounts/music-folder.yaml
  - ../../../../components/cephfs-mounts/tv-folder.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: bazarr-scripts
    files:
      - subcleaner.sh=./resources/subcleaner.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
  - pairs:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
