---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerr
  namespace: downloads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-blockpool-nvme
  volumeName: maintainerr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maintainerr
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
      pool: ceph-blockpool-nvme
      staticVolume: "true"
    volumeHandle: csi-vol-cc25f117-da4e-4114-9cc6-18872afa972c
  mountOptions:
  - discard
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-blockpool-nvme
  volumeMode: Filesystem
