apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:eX3PrbyTVsfiDufJCb/tjQI=,iv:ElEHpWD5SCtW8c2Uoqp9y7ldc+fft/2wa+teeqUw1jE=,tag:ALqhsjpNmt182dtV+w7vqQ==,type:str]
    #ENC[AES256_GCM,data:M8iPPorFIxTeyd1Ug5UMCFaU18Y81nB0Gh/yn9hdHvEoQQzjvAuSDWUVt6eXDkcaFRLGVcpeRc6pQ5OquBBys4o=,iv:4pMj13b1/zHLvfdecXXBleDfoTbHTSEIyGFf/vWyDcw=,tag:4PKMIcUlW2WsoKfNxh0Etw==,type:comment]
    #ENC[AES256_GCM,data:9c4L4tx81GImpKWZgW8kk7zUc/fDelifHZM3MhVbKA==,iv:i5FSqY1/+WipiyD8agU0LGfBguWhaErTB9MCPDIlGck=,tag:3cXXaDiW1jmwOnp6mZFdtg==,type:comment]
    #ENC[AES256_GCM,data:dFtZtOleX53wARMpoP5OtRFk31xv+g8Lcq3zJZkUCQ==,iv:nn24Jhp2+8+2F2C+m9iEs/8sSr0rfh4cBzbbadXCqvE=,tag:g6Oqw8v+TU2aU1q6O9eLmw==,type:comment]
    #ENC[AES256_GCM,data:ck5ZuuqvH6L46PwifHjhNeF/OswQeukhhowcWzCvR8k6n4vyEMH/mA/pqksBeNL9YYlNNmE=,iv:yLmKjlCYhR3aZb0A9+1p7lew/J0Ood8OCzJqpyMLz+c=,tag:OZ0ydVB7VhLDDfejXbZLpw==,type:comment]
    #ENC[AES256_GCM,data:ity+Yh9uLmlGT0PoRC/mSF/Z+gGESJic6z2wJKrV+UF1+5LqlBI=,iv:iH3Rkujp+WvF4aZg4WtWoV8D6Fr7k71EAhKTgoZgW2A=,tag:aPF/CUfMHpjXi2vTJ75VCQ==,type:comment]
    #ENC[AES256_GCM,data:+RkQoYL4wHKswR9tBvvQ8fClyZ8KIRzvLPeIvnoQXVKYIg==,iv:rNgou1EiBrNgQTCAkUe4RSOUia5HdLXgLMeLoQdepYw=,tag:s0MGylEu18R35d3kTuG7BQ==,type:comment]
    #ENC[AES256_GCM,data:TY3bpYhANFzsjXfv3JOvPhByZUMG8iw9Eq2XUHzhpOBNvHYjbF1BsmLGDf/xEn2qmPe0hP3pIYSGWFJuYg==,iv:CIbtcVe86bOCu7Cnb40viKvDQ77W3ePc/V7ANHMup+c=,tag:w3Vip7hrM/0vwitXhkt8nA==,type:comment]
    #ENC[AES256_GCM,data:OSXr6OqLRzDgjXeoHt7HBbgcgIW4zk+e+UbY,iv:uNt5/837J6TJZZam/xaC1tfxBdTytUiq/KxVs7NJzRY=,tag:MXQmUwj8Rs07Vd/ydJeNvA==,type:comment]
    #ENC[AES256_GCM,data:DO4IMJaJeOmJxMJljfkQFe+J/SlVzJ9aXONqpz4lXmUBP5jq00iqPsPoAluZ,iv:f567wc0q+nSdDlDCuGcInt1mzcvULidtcA0z9f4iR/Y=,tag:/jreR741mRT6W5Qrz7vj1Q==,type:comment]
    #ENC[AES256_GCM,data:ryG1VxqiOv2QgTlNhyyi01Cu2QYUD5A9CUI2qmGlNBjOrpPiRg==,iv:CgRivXF4MZTbtllVLjxdZjYWR0KJhS+fuTTggc1OSf4=,tag:NGxhanDQXbL3mgXbbtgaPw==,type:comment]
sops:
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvclVkcWJ1clFKcWlCNi9J
            bGF0ZStRZDhLenA1Q01La1B0SXFXc0lEQkdvCi94YmkxYk9DdGRheDcrU3NXQVR1
            SFY4UndXcE12OWVKSlhIazdYWGFiTEkKLS0tIFhoMlU0ZlpZcE0wMUFKV25ueGxP
            MjVIazkwVWF2UkxiT1pGZ0lYakpOcjAKKocq88Cb7JmM0eTcfzuAiOBUv4Wihyjq
            h4BpWRzN/1wkJM4qMUT4pRCQncidOP0kyaLWZlDsVgjKe3SMMUdTVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T16:51:35Z"
    mac: ENC[AES256_GCM,data:qkWoewtCifE0M+evITCruR1InBpHJEqc5Ko4oQCjBWpRVA3JRfgU4UUPXNlMOsN2/Uq4PHhbbqXdULqIGunrAt3yrY6dB2gvoF6QmaWC7/0sqD7uYYb+JhmYQh0fbSHeHt64ooHi1USIcTjO9Zkv3nhT+/t3pfCQGzJoVFnK0nQ=,iv:6GgM5+WoZjpfm2ffX1id1Ls3s9Hsij85GFXO5snH0qo=,tag:IASZ4QLDiOCFgRRh/ugKHQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
