kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: emqx-secrets
stringData:
    init-user.json: ENC[AES256_GCM,data:9u1RdjGDnd8kxZJ4hHUnJCdGdj7dI0fRt/OBBuEEOz/N+ijE2lif12ImQ4eAsFrCxBcvONkOVT34kPAI81MIvLU8YatjBTdHbZppsHVGBCanhPcAA8dPy4EMb98pp20AyiyEU59wjhmwrrqBzfp1pclmXu8EKbxBI/eiD2t8NB8CPAbhGiFh1qjOeHuFA8PCAszZ4ApsvA51gkw157hW+Z3pqs3riVE3w27ABtRH7B+qpF+d1ABE4q0l9Qu53hxp1GYz0QR+5pcadAAlpQmffDMnPY7cQym9Y98VcnbXpZeBfSocAAT8rEBn1eeuwrCTCx8wLff1A1jmSZb1NbmJecuqfNb8rxw6fOjY7a2vlyMo2LwjulFPjl1YK+bTsymv/XigEOc7N18zlxTCNHK2OwAS5Sar/wFj/iaXhwCFEnU6sYoxpkvSQarYg6IXxNC+YP4yQsVL+RM+yFFsJjCl5YeySbXjhe7wW5t29FIOtXWmc0N5hl0M3TtFdDbiVExNzxB+VX+pbIdmzJXwxl3AN6k9/XCz4rJBsmfsxoG58sj+y3sSowvuLxGcLLqkmjHSpaP3p3BnPi83YeX3uP0QWd90nVQ8LAHwulYEM59sJ8SViwXg6ZQrl8lVk6tors5ZuhsKcdcVlYrvdLkGu3o1g9ddPlvRiy2+B/9GCxx9sedIBWP2ZAPpBW63VDHIZZpQq3ONJ4cVpyr8282VoQoOBGOCFKjw/MCECZ99pcZMv11hZFgHO+mzBm4Jbq1ohje+3v6eac57PHkSRCcuU6ksMEoBRuMVQTOVA0sOlLI4ScH4so+BIyI97rj1cUQPaGlMAF5vFzkoHnxUCTkRKSu2KQ32rSFtBntwRepmtXaHtEnWcemL1MuN3Q==,iv:7u5OKVwjEdJvRFmL+Go2cWq40ZVCqAoD2lcrYWLCHuY=,tag://V6YOQ0fwuyJHZEdS/PdQ==,type:str]
    admin_password: ENC[AES256_GCM,data:okEJX34P18eW5g==,iv:VHXEbmPKnXr9aDNiXjwT9cp1QYZTJIwRX0WVCaynzig=,tag:/vBMaLoPyM8rB7bSlReBlw==,type:str]
    user_1_username: ENC[AES256_GCM,data:3qMz/5sKUA==,iv:6Iw5VFHPj+qf6wq6+Pku95rC+b2UoVRUTqBs7/Jas6w=,tag:2iJ9EsLqw/i9H2qoFu7nFw==,type:str]
    user_1_password: ENC[AES256_GCM,data:x1mY8ifw2QXWQ/Y2gMb5iQ==,iv:ZhyQOacu9Pgct7dMy9pKcvVzjhtFm9C7UJ4P4coo5Ik=,tag:fdGmxwuuc8EKe+h0euyhzA==,type:str]
    user_2_username: ENC[AES256_GCM,data:1oi2I6GbCR05riPKVxM=,iv:rTUkVxi1mqOJxwvdzVpMlfzm+5iE2r/Y37wTpLdhqQo=,tag:eLBgFtr+8RMEwhIrisAgEA==,type:str]
    user_2_password: ENC[AES256_GCM,data:UrBirje6f+WneAL2QuXtFA==,iv:dYs3j57BuV3tcsYTUZFC2/GNoTUuhZcokR5mfWcEvTg=,tag:PwH4rYjaHvBL+UywsmI8Fg==,type:str]
    user_3_username: ENC[AES256_GCM,data:pVM2m2r/fPU=,iv:us/SGbPbmdXGLDrFias+znZViNA9gyFxzatx7jb9Xqw=,tag:V7mp5ZEK+MN3H97jt+yxvg==,type:str]
    user_3_password: ENC[AES256_GCM,data:z6IXl2d7DdD8gqOEnY5V,iv:sJjCELmNFz9xiKKKygzz1Pfal/0miyYTJtAWXE7cu2U=,tag:SNkRgCP9mR/ANIaVoLoIxA==,type:str]
    user_4_username: ENC[AES256_GCM,data:REad7e1q9mVuT2U=,iv:Hmp6FpQ+0rCgd6/+xO9l8922+4IZr2SJymy7/eeeoNY=,tag:Igzd61jKMHKpFS/Xz6KRxw==,type:str]
    user_4_password: ENC[AES256_GCM,data:LolOi4Fv9kYRM4QhL3Puig==,iv:tl+lW84IbxDsYT3/wrJFVsiTA4P+NAZCMlgyoy/oJDQ=,tag:MJdBzwpjFAnzeqjySKnfXg==,type:str]
    user_5_username: ENC[AES256_GCM,data:ixjA0w==,iv:LbazdNVLrP05oyaOUPNnXS3WdPwIEGj7FqilQjXRIag=,tag:SUvigtWDWviNp/DRZc9jzg==,type:str]
    user_5_password: ENC[AES256_GCM,data:3IDWQRs9j668Uk9s++dmZg==,iv:yxF8b9wMXrJ1LVawwq+ENlB/37R0Z2ONiHOc0C0rat0=,tag:BPAGaavDxfEYGFQtHQ2Iwg==,type:str]
    user_6_username: ENC[AES256_GCM,data:Yu9WbLdCbQ==,iv:uGpgvqNkFS/McSf50BqAdt0u1P0KTnFFp8qxrpNwS80=,tag:PmM2XCCtyulCeaOFnQY8sA==,type:str]
    user_6_password: ENC[AES256_GCM,data:UeYROFk5ni7e57nZ59pIjn2OENqUtw==,iv:o9ONmhVKmzbPL7NTL4rVpaVN4FLJzcZG565AapGpeC4=,tag:zWpRlsnkvJvFY5MQgkOcZg==,type:str]
    user_7_username: ENC[AES256_GCM,data:woLdHmWn+vw=,iv:ZeqaSQFzqDFfLaL2pKK+1dT0WDnFvcmeKBsPfVYTqrg=,tag:BYdgCTXjbY2gwJmHJioRZQ==,type:str]
    user_7_password: ENC[AES256_GCM,data:uMv1QenMUfJAUI4MJtpM+sAM8YQ=,iv:6a+qaYKmoUyBkrVh6Q4oLxYZCeYYC/AwVOBaKu/Rt/o=,tag:DuJc2oyGcqDoEnQ+j5k2tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNS1VTTGsvQ3RXM2dVY0M5
            VHJVeXlaSThtSFNERFdaMDFRdHJPUnRTNGcwClhsa1Fmc3BaODEzTEprT0lPeEEz
            TEF6cWw5MmhRRjUwR2JXRmx5a3prd2cKLS0tIFZDT05xSnhXdXExRHF6OVFBN0RT
            ZytubnpjVkZyeDMwblpCNGZ4dEZTcXMKpFOcgiIGzcNQc9FfmUQvt7DfE6s8UWEJ
            apg8DqpLbqabP+5e5wmXeb7w8bH3AwAyUaWZHwhkEpobQRV99sfGuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T16:13:23Z"
    mac: ENC[AES256_GCM,data:115FZRJKU9xky7qp3Rfjw4xNA3dtRpgHYXkdTJMrzr3oc4lwiTeKVK+Z/3Qc8wBVm6eXKLDkgucliP70jMfqT0I9HeID8HN5N8w7RYh5H8SsFVKCpc+XMX6LkcekhZBqqy4lsX4BYkDt22u5xdTPjCZsO8BU42EAdYdNRH37frQ=,iv:tk0DJOeYoU1cqmeQdISODaJYpvB4e4NrQ9e0Hxj4RTI=,tag:7pmQZdlBZXCrznh+cdvY2A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
