kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: emqx-secrets
stringData:
    init-user.json: ENC[AES256_GCM,data:uYvwsrWvtjqwnRlfDtE9/PBsoSvszaEsBPvqtjHQ2BSm6Hptr94EidSWGMiAqZCfiv0L+Cgzb8GltxL2bEGx4TjN+KH2MpYZfzuBaB+u,iv:WoWu7ceTYVUxACIVXmAZXXcrDjahCfMN7RnnXsMrTco=,tag:TAqMNgfwjbe3tCGReWzkpQ==,type:str]
    init-user.json2: ENC[AES256_GCM,data:hyeViVKB3UBLCftCaBc51WINoWUKKYDqS7ELKMVjnmlcw5foEqoVoxWFp00tlFavCV6XPxwI4c9vJhu6x7Ht1SN+NFpnZm2Jh4KNyGz24pEw9fW9l1rnWNKUyFPgfg8HbVisYs7w4QL2TnziqeBJ2IOUXGrs7mgiOBHdsoM525i9+C/c/ZMp1/Wz2K13ySpyzxeZ6669v1xKTO41JoS146dEUpAfIluCCnazRQWVl1YIy8qbuyylc/G+0zzdRkshbmisj4nN4nsUADnVWGvocInNx8jfc2UijNJYs77xZk7EARN5xpy4w8q1HgcKfYJj/B6yaEhpFDXRGtjvb+ryHOPhjkVldhpn4GKK/5NEz0b5sjW4agYqmmzZ87tHHd94a+uLutLpwDS/gIPorIXFdcnfsqOVBkJDYBZtJTUSdDreno51hmRtku7FWZgVL+oKty8/kd5wZr1MRDfHsve7rZC+EPPS7bPN1kXsaF8GTu35bFgm2ughoNOPLrTadedBWAYLAPBsm24Zk1kgtdHtovLCWLkGJcKgk4wEEAcAXFgiKPuiugmKYqhodyNAmu9/WkNEdw0LqnPxc4diLjBUx53Ny9YPLqldbe2F1eH+ysXDT6iEHggr2tkieOfuz+62ytSWUsQhlt9pwZm+7QgHkXyhC4Lfr1Pw82UsVbdwZvs3GN7dKMj2HeJfMZFHDlFAy6wpL2Q38AkPh0OyyA+jB6Fniymq/PpgwxrkzxNTmflJS/KHtcyQJziCE7Bp+WQR2xm2D4/i/BoyUWEvmpKqNQX19mDTD/L1fvPrI58JT47qSd8I/B9wwL4L2s0lcvXDi+qXE8ZvPk1kLrGQvOtW1DmWeZAXM2CYSAOzZfetlMp4jfT6nWc/PQ==,iv:sEDlnNrLrEoVf2Qt9PtZSNmZ1xKqAqJU3rrCzQltpaA=,tag:Widsyw7bkCYfvJZEDlXGxA==,type:str]
    admin_password: ENC[AES256_GCM,data:okEJX34P18eW5g==,iv:VHXEbmPKnXr9aDNiXjwT9cp1QYZTJIwRX0WVCaynzig=,tag:/vBMaLoPyM8rB7bSlReBlw==,type:str]
    user_1_username: ENC[AES256_GCM,data:3qMz/5sKUA==,iv:6Iw5VFHPj+qf6wq6+Pku95rC+b2UoVRUTqBs7/Jas6w=,tag:2iJ9EsLqw/i9H2qoFu7nFw==,type:str]
    user_1_password: ENC[AES256_GCM,data:x1mY8ifw2QXWQ/Y2gMb5iQ==,iv:ZhyQOacu9Pgct7dMy9pKcvVzjhtFm9C7UJ4P4coo5Ik=,tag:fdGmxwuuc8EKe+h0euyhzA==,type:str]
    user_2_username: ENC[AES256_GCM,data:1oi2I6GbCR05riPKVxM=,iv:rTUkVxi1mqOJxwvdzVpMlfzm+5iE2r/Y37wTpLdhqQo=,tag:eLBgFtr+8RMEwhIrisAgEA==,type:str]
    user_2_password: ENC[AES256_GCM,data:UrBirje6f+WneAL2QuXtFA==,iv:dYs3j57BuV3tcsYTUZFC2/GNoTUuhZcokR5mfWcEvTg=,tag:PwH4rYjaHvBL+UywsmI8Fg==,type:str]
    user_3_username: ENC[AES256_GCM,data:pVM2m2r/fPU=,iv:us/SGbPbmdXGLDrFias+znZViNA9gyFxzatx7jb9Xqw=,tag:V7mp5ZEK+MN3H97jt+yxvg==,type:str]
    user_3_password: ENC[AES256_GCM,data:z6IXl2d7DdD8gqOEnY5V,iv:sJjCELmNFz9xiKKKygzz1Pfal/0miyYTJtAWXE7cu2U=,tag:SNkRgCP9mR/ANIaVoLoIxA==,type:str]
    user_4_username: ENC[AES256_GCM,data:REad7e1q9mVuT2U=,iv:Hmp6FpQ+0rCgd6/+xO9l8922+4IZr2SJymy7/eeeoNY=,tag:Igzd61jKMHKpFS/Xz6KRxw==,type:str]
    user_4_password: ENC[AES256_GCM,data:LolOi4Fv9kYRM4QhL3Puig==,iv:tl+lW84IbxDsYT3/wrJFVsiTA4P+NAZCMlgyoy/oJDQ=,tag:MJdBzwpjFAnzeqjySKnfXg==,type:str]
    user_5_username: ENC[AES256_GCM,data:ixjA0w==,iv:LbazdNVLrP05oyaOUPNnXS3WdPwIEGj7FqilQjXRIag=,tag:SUvigtWDWviNp/DRZc9jzg==,type:str]
    user_5_password: ENC[AES256_GCM,data:3IDWQRs9j668Uk9s++dmZg==,iv:yxF8b9wMXrJ1LVawwq+ENlB/37R0Z2ONiHOc0C0rat0=,tag:BPAGaavDxfEYGFQtHQ2Iwg==,type:str]
    user_6_username: ENC[AES256_GCM,data:Yu9WbLdCbQ==,iv:uGpgvqNkFS/McSf50BqAdt0u1P0KTnFFp8qxrpNwS80=,tag:PmM2XCCtyulCeaOFnQY8sA==,type:str]
    user_6_password: ENC[AES256_GCM,data:UeYROFk5ni7e57nZ59pIjn2OENqUtw==,iv:o9ONmhVKmzbPL7NTL4rVpaVN4FLJzcZG565AapGpeC4=,tag:zWpRlsnkvJvFY5MQgkOcZg==,type:str]
    user_7_username: ENC[AES256_GCM,data:woLdHmWn+vw=,iv:ZeqaSQFzqDFfLaL2pKK+1dT0WDnFvcmeKBsPfVYTqrg=,tag:BYdgCTXjbY2gwJmHJioRZQ==,type:str]
    user_7_password: ENC[AES256_GCM,data:uMv1QenMUfJAUI4MJtpM+sAM8YQ=,iv:6a+qaYKmoUyBkrVh6Q4oLxYZCeYYC/AwVOBaKu/Rt/o=,tag:DuJc2oyGcqDoEnQ+j5k2tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNS1VTTGsvQ3RXM2dVY0M5
            VHJVeXlaSThtSFNERFdaMDFRdHJPUnRTNGcwClhsa1Fmc3BaODEzTEprT0lPeEEz
            TEF6cWw5MmhRRjUwR2JXRmx5a3prd2cKLS0tIFZDT05xSnhXdXExRHF6OVFBN0RT
            ZytubnpjVkZyeDMwblpCNGZ4dEZTcXMKpFOcgiIGzcNQc9FfmUQvt7DfE6s8UWEJ
            apg8DqpLbqabP+5e5wmXeb7w8bH3AwAyUaWZHwhkEpobQRV99sfGuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T16:55:56Z"
    mac: ENC[AES256_GCM,data:TQVhPZrVB3yxdW6V1aA4ETtfAREzpiA/63qn86VEdodXiAAcegzeh4kHGziJOD1lJm9Qg9hci0jG3rzBok8GzWds35nCzfZ8lPsr9XFHhfx02bw+IdmhZgAlLJvADph3KmOFmGfSs68Fedmcb9xZJsdGlORtdyzj7J5fSGdT5Hg=,iv:abcIs329Q8oQpuF+X1AXD5ciZK5YKz1cWRZktR+BU3M=,tag:LGFu33MoDYCXBzNCqBu/ZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
