# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app lldap
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    # - ../../../../components/gatus/guarded
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/database/lldap/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
      GATUS_PATH: /web/index.html
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_CLAIM: lldap
      VOLSYNC_STORAGECLASS: ceph-blockpool-nvme
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false


