apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    sops.agekey: ENC[AES256_GCM,data:MeFVT2VwV3J1SRFXYAOpeeeYoZZhlnYrvvOg7jE+/ZbqN/4y/R5nHr4IeEP1NRYT4NN+dpRGH2MGCS3bBW5RZDuoNdgksRSEpxA=,iv:zRO8vJ6hEAYcpBiILxHUf+TaBJMwrpg1Mb8w0ury/I8=,tag:Cce21MiavHVxyOeAEmmuVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYitDNVdLMHVmZ05RVEQr
            QXNzelFjc1JXTEdvUGZXNGVhUTV2T2FxNUdnCnJWSVFqYjRJOVpMTGNacHY3bU82
            cjlUZGRGOW1yaXRRYlpmU0tiQ2lVYjgKLS0tIDl6OGwwTEMwSUFuVVBWOTJ2MFhp
            WnEvOU9HNEJkTk4wVUlJME9rbUd0SHcKOpG7HYLCeMtiVUXimw74V+9f0/xMsaLG
            vsWTw0HDevx8d6eVtYQGGuXoWJj8BzwqyukH7jBa22v1fDMPC9wodw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T00:44:24Z"
    mac: ENC[AES256_GCM,data:tY7nAP+rq1EArabg52eJY4Hl6dVkQBaLUihxlO7w5HDbVeARaJaAu2yYS2/dsX4Bvl2LlRNSY0ThNzVzU2Ni9TjwQAa23ocCob0TaiVpEJEYwWcRa7dK01YedkvdCuuVyd7nJb48x9GyYo0CE14VpED/f0yei3ussOw4TfDP/e4=,iv:blEkPKXkCCayX2JfR8hIZWvhPtM8zuosZIlJEgTQ6Lw=,tag:dl2mrLR2NDxm0ae+V4iz3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
