apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    #ENC[AES256_GCM,data:tHKfnHs+F6vaFkbtz5xt,iv:GFOrfutdg5fuIFEgxqtugiBDFNysl93KsxbEjCrpeHM=,tag:Ja2lwMpeKd0LCqmq+cOXHg==,type:comment]
    #ENC[AES256_GCM,data:iiz1YZ/GQJoM12LJQpREIf/0S/E9nQX8mJpHwE5sDcl8pCY2H19mirWmrJil6BbBXyweQzBDNVb1V7vqfWsnUDRz0AIQQZKYkeGx6JCbIIk/9LnR26ItlBT6fE8kCh8cOigpmGlhqpSbYpyyDF7Nq7ZkDQTdd7eCsCg6qKK4OLLl5GcJa+IJyQAjjqGcFodzOmpc0s66qDEHqUgwbY5NJdQCMv1iprtfbS/J1jGQ5PxetOBJX3RVxecdwaJjWu/Xny+4y4qvw5AWhLIJ7Y2deudSaKzcapvxES26mTUxkFbRtncGpz9s4bNnhY08REj2yz7yb//S3jMz93vA60YE4pQLkrPAJA==,iv:+EMT8DZu0GyhDKTYaVhET7zNUKo9YaPa12F6Z2YHu+c=,tag:N64Io7SKZkI5QtalfjZnfA==,type:comment]
    sops.agekey: ENC[AES256_GCM,data:Hkhgsb05O9zjHmHDBr6hAr7EU8GS2oPKNeQTLW6MufVaD2p9aXgShb8gLAK5Egfaz77tU4yZsWymld5ekVvBXebNEAMB1jlgEHBmU3jkfvHsodxP6Fon1PbVJ6MbH60R/i1gkAl9e14WX4xkmvl1nHvsXWn/A6cj6jFb0NP2MbEfI47QFiC7yfP4dGknugqQswz2Ir5U3p7sXohyAIAU91oMN0pQWwwuHSir4A2cw/qANXbFO8fLkCw=,iv:6VEQQaKtfSni6O1E8iiph9gaEB49bfKAl/0TAqam1Kk=,tag:LXWi1JVnstKXF+/iXOu5+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYitDNVdLMHVmZ05RVEQr
            QXNzelFjc1JXTEdvUGZXNGVhUTV2T2FxNUdnCnJWSVFqYjRJOVpMTGNacHY3bU82
            cjlUZGRGOW1yaXRRYlpmU0tiQ2lVYjgKLS0tIDl6OGwwTEMwSUFuVVBWOTJ2MFhp
            WnEvOU9HNEJkTk4wVUlJME9rbUd0SHcKOpG7HYLCeMtiVUXimw74V+9f0/xMsaLG
            vsWTw0HDevx8d6eVtYQGGuXoWJj8BzwqyukH7jBa22v1fDMPC9wodw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T01:09:14Z"
    mac: ENC[AES256_GCM,data:BmE8EOsFJ/EAdz4E7+E3f3rHHTV29KLuBpLookHkOP+oPM06cOqCEwAYjt85aV2+r5G3a0wKoICGP9POc/P1IMcdIdprnRQmkEYJGp6XPu4nntepNkrdEUTgpyO6gmJoz2WVuv5c+x2PYni7hYb+EbKctgPIl+qsyrQwy3amd0k=,iv:BfzZbR+0STeIZlr9QyDZMqInA92s8u8d5UhpB+xEzNU=,tag:e2udI65D/lFBeOfW4Hqv9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
