apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    sops.agekey: ENC[AES256_GCM,data:5l0KXFM9n/PEu2NmneGeYr+xFu2c5EYGxiq9lsh4m7qlrsKMTyWjjTqI99SdRe4lhZQ9WVrnIUXqKW7JWZ++KNUB1vtvmj70Nf+ZzMO75Rt9WVc016LukCy6s8E+udWtkJQgaA==,iv:qp6a07BxxDBo9wnZ5MrIc5tbR9u12h+ld6WhVJS0m1k=,tag:rd9M4ltFadMbIqrDe5t+Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYitDNVdLMHVmZ05RVEQr
            QXNzelFjc1JXTEdvUGZXNGVhUTV2T2FxNUdnCnJWSVFqYjRJOVpMTGNacHY3bU82
            cjlUZGRGOW1yaXRRYlpmU0tiQ2lVYjgKLS0tIDl6OGwwTEMwSUFuVVBWOTJ2MFhp
            WnEvOU9HNEJkTk4wVUlJME9rbUd0SHcKOpG7HYLCeMtiVUXimw74V+9f0/xMsaLG
            vsWTw0HDevx8d6eVtYQGGuXoWJj8BzwqyukH7jBa22v1fDMPC9wodw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T00:33:20Z"
    mac: ENC[AES256_GCM,data:M1ao2hxPmRlsQbRSm9IdYupfCaQrC08/XnCsJpOF3WFWT/fgxZZNU4DoDsUh965f5vyEzOob/v7pcsxIFz6MkohWTSjL+qO5UFjU4aJuUdn0QXEGf/BBloN9JeGEl5U0w5736i1JRnbauaLp3CoccPZtn6CDAZJGTJNvwlvuDwc=,iv:koJ0VZpnjzCjX9Rx6msXJ/1B5PRgf4INGid78XN9NUY=,tag:PzOjB8wPVeDk6Dm+/Ln4ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
