apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    #ENC[AES256_GCM,data:tHKfnHs+F6vaFkbtz5xt,iv:GFOrfutdg5fuIFEgxqtugiBDFNysl93KsxbEjCrpeHM=,tag:Ja2lwMpeKd0LCqmq+cOXHg==,type:comment]
    #ENC[AES256_GCM,data:iiz1YZ/GQJoM12LJQpREIf/0S/E9nQX8mJpHwE5sDcl8pCY2H19mirWmrJil6BbBXyweQzBDNVb1V7vqfWsnUDRz0AIQQZKYkeGx6JCbIIk/9LnR26ItlBT6fE8kCh8cOigpmGlhqpSbYpyyDF7Nq7ZkDQTdd7eCsCg6qKK4OLLl5GcJa+IJyQAjjqGcFodzOmpc0s66qDEHqUgwbY5NJdQCMv1iprtfbS/J1jGQ5PxetOBJX3RVxecdwaJjWu/Xny+4y4qvw5AWhLIJ7Y2deudSaKzcapvxES26mTUxkFbRtncGpz9s4bNnhY08REj2yz7yb//S3jMz93vA60YE4pQLkrPAJA==,iv:+EMT8DZu0GyhDKTYaVhET7zNUKo9YaPa12F6Z2YHu+c=,tag:N64Io7SKZkI5QtalfjZnfA==,type:comment]
    sops.agekey: ENC[AES256_GCM,data:LEvd880pZKLSPP6faGYo5s4F8Bk0i5WnqB0Zg/EGeC5ckcGakb1AZd+BZYaEbT9PChR73VxZX9wvU2ic8GE8b9gufr840M0KkTKLUhgayeKIqt9V2SGn384xeRmrYfg4pCWPf7LrvO7/o9Jr8UQBemdIH1txt+OkbKNMNnFaczq80QmyE7W9iY1g2l9MPZ6bLT3oCUbh7rzeKnHzCpTHX4hxiHuqYaugNJaBVi1GerJqdoBNtEqyC15oxP8abqx2vxFMKqbN2MweFzoQc5KDgXU/3hFbsZnGoLRqv2EpgvpgQk3GOA/42pZK3W/RGVJTu7/UvAGGKz4=,iv:BcLCot7AZdTCTrce1WYwLwkcqR55ea9f1ziHMk65mUU=,tag:XCLbU31RGLF4+qoThIxMjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYitDNVdLMHVmZ05RVEQr
            QXNzelFjc1JXTEdvUGZXNGVhUTV2T2FxNUdnCnJWSVFqYjRJOVpMTGNacHY3bU82
            cjlUZGRGOW1yaXRRYlpmU0tiQ2lVYjgKLS0tIDl6OGwwTEMwSUFuVVBWOTJ2MFhp
            WnEvOU9HNEJkTk4wVUlJME9rbUd0SHcKOpG7HYLCeMtiVUXimw74V+9f0/xMsaLG
            vsWTw0HDevx8d6eVtYQGGuXoWJj8BzwqyukH7jBa22v1fDMPC9wodw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T01:16:52Z"
    mac: ENC[AES256_GCM,data:Y3KuR+pkjNnFWh0gpQJFG0R6fuZRquxWsrgHBjp9qD1LatrwJd9yDGFyJya7XO3ya2mgXmHJ+fdPDOSCwicLWMHryaQ1LeYz9knaUNILDeLrSh/sYJww3hSlqsWAozibo3Ml2zLyCylrutO7sVoIyoSwOGvyzRHw88fdi7wWO2o=,iv:MirPsg11aGgFclJSj1Ka/OOcabcLwKt5HS8HYf5KWJM=,tag:27r7j4MNoM7xNHYdyDD7gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
