apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    sops.agekey: ENC[AES256_GCM,data:YJmODBxTtE3ZkPzyzZIqHyaVpd1yYn8Z36aSvyq6tQT1g3mKC3beD5pD4/uj0Fo01yfkVGzoHgpy9S2csvS2lqePFZ0A5Tz+YSU4boQeiVMatK6ZeoaNh6o04hh1bVzsJ+vXFprFr5Peocis0a+L2GgbzJX5ATiLx2jfff8F+MBrcIpI6YsgfaAGUN4ro6CeveQS6PA6BefsZhvwLpKnWvL/pQ6jNCc8wGzgFLfuRccfFaTmSKx3,iv:tcgL2nA1mA0YW5Ko1JLsCnoqU+06jPismwjMQNlkGfc=,tag:hVVnU84HrEUbjtT+4VQ8Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYitDNVdLMHVmZ05RVEQr
            QXNzelFjc1JXTEdvUGZXNGVhUTV2T2FxNUdnCnJWSVFqYjRJOVpMTGNacHY3bU82
            cjlUZGRGOW1yaXRRYlpmU0tiQ2lVYjgKLS0tIDl6OGwwTEMwSUFuVVBWOTJ2MFhp
            WnEvOU9HNEJkTk4wVUlJME9rbUd0SHcKOpG7HYLCeMtiVUXimw74V+9f0/xMsaLG
            vsWTw0HDevx8d6eVtYQGGuXoWJj8BzwqyukH7jBa22v1fDMPC9wodw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T00:51:30Z"
    mac: ENC[AES256_GCM,data:UjmIOfHSiOneyYcqm246o7wy79K6ZyQRXPeff8MhdCZYuHEsDt9TXScA/on9rnsJ8bIdmDmnJrF6CKYPGH1uWmbY8c3avs+aDGHjnKeIk+5aL2rI35PuO3Vvk8MbfjyseQqa+TcA6YEjJQYby2gra5fgaMqP6z7jfZpVsZ5Eyxc=,iv:Zn4Rf5Cysov/cnsR+G6/PeTtxK7Oc2WzJ9aDLN/+n0Q=,tag:RhibtOwgyFuphIXFyY0gpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
