apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:srI4b85sIvO/yIQ/SX4+HUQ=,iv:KT6YAZgBBKQGIY9QvBZAO59v8rnqGjadD1ko5PqA+Bg=,tag:CRzLvxuqdLfevHI0Y04v4Q==,type:str]
    #ENC[AES256_GCM,data:W5u6WxcVAxjpVcKk4Y2MrXxuRqk+5mpIFYrsaCu4k+ipvl62/s/Z32veTdZDiUnvtmK5nAEkH5iyC+MBG2wnCnM=,iv:Bam2bD6jw/oPn75armqVV/2minFiaE2J29pOQwA7AZo=,tag:r6d0oWBv7DjkeP6jAcKZeA==,type:comment]
    #ENC[AES256_GCM,data:B6GbnYnRSBDQzpLLcU3KJN+0QT5vM+IDuh3xZvcTTA==,iv:LZ4Ws7bVehJWnEXj+QfufIPNV2lCqIcFRmocIR2lZt4=,tag:IW4vQwW1ZLUCmn6bXDW7Mw==,type:comment]
    #ENC[AES256_GCM,data:P+XBVGMvl1QwA14tYoNpYX42r35R7+/8k/2XOPU5sw==,iv:wFWxKzbEsOaZPlvl3lUeaGoIVXdi2UFfPFi8peGpS9Y=,tag:tIlkzCe8hkW6QqaaR+Foig==,type:comment]
    #ENC[AES256_GCM,data:K9VY94CsDRd9k6P3C0lAi6zOrhQ+L/ChDdCQtFdflFQpxHKSvBWSi08c6pOtLlUAXV5x7fA=,iv:XkJDPdWobsOwG68YH6IhBwyF/8oVi2tTImTQUOOr5TE=,tag:Bh6grfj/hDufAE4I0twViw==,type:comment]
    #ENC[AES256_GCM,data:W1kFK878A0y75jFM7pBrpvX/bygvdp9p0nv0NHPmBVStCx/Ul0M=,iv:DTZm8qgfSe8uVa/eFceQvA/u9NsrimEfir0v2lnq/ag=,tag:x5pN4V2OT+vG/PKkI08meQ==,type:comment]
    #ENC[AES256_GCM,data:DYNySC8mcQsG/NZjoFNcgP+Eg6lv8D8HDrOXt6HPavch+A==,iv:ww4f8dBjhxK113dfg4b5hg8f2Axmjrnm5R9CEinrYfc=,tag:StDBm1SNhfZgJwTA1j6UdA==,type:comment]
    #ENC[AES256_GCM,data:TDrn3gMRagxrz9TJ4DZJTEN+rVTZhS5uCYdxfcLF8K50ZT8R+dpZZrf/g/H5JOVML0Xu0YcUiOVHHghFAg==,iv:DAJXWXuPiQykf2isXbzbCvnY3WUpam9KM/6madwBweM=,tag:HIe3161xBJ47Nwe6IWMntQ==,type:comment]
    #ENC[AES256_GCM,data:NTtHN3xVy2LDQ2WmRhn2Y3jRpaGeLd7mXlNF,iv:HUJxSy+NwfCKuBGmvShBcPD5IqKVZbb7YhIGBOPf7pI=,tag:nhfplnpsQ0jcJDSgcuhIdA==,type:comment]
    #ENC[AES256_GCM,data:akI15OVRqiSKwTALkogcO0+SxeR307pPOtyhAIrj9aSbtf95nxpfrIpdL2OI,iv:iO+XaIzQbTWGD0VOcJNkF2LeIJki16UGu5RQCWXTYwo=,tag:P0AX9/t7oRQCkbQ7EeBOaw==,type:comment]
    #ENC[AES256_GCM,data:JYG/zXgQzkXCV5hMaGyRhb/CD7pauuWMehj6bZnoKLDtlOXOkQ==,iv:2kSW+EzVsBNtJvLTTigzftLkyPmeXGW3joR7nBqh+so=,tag:uQ6wRuhOz+FSI1z0j/sIEA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvclVkcWJ1clFKcWlCNi9J
            bGF0ZStRZDhLenA1Q01La1B0SXFXc0lEQkdvCi94YmkxYk9DdGRheDcrU3NXQVR1
            SFY4UndXcE12OWVKSlhIazdYWGFiTEkKLS0tIFhoMlU0ZlpZcE0wMUFKV25ueGxP
            MjVIazkwVWF2UkxiT1pGZ0lYakpOcjAKKocq88Cb7JmM0eTcfzuAiOBUv4Wihyjq
            h4BpWRzN/1wkJM4qMUT4pRCQncidOP0kyaLWZlDsVgjKe3SMMUdTVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T15:38:28Z"
    mac: ENC[AES256_GCM,data:xMmkcgrVR6vMG7Vcgn8yNgpN+c/Q9yc6NaYM5JwZgtptaDJdjmnCjQP4LsQ/6nSShSP6gvnPtMEM9iY+hT1TF0GqWLMy+jFFEsRaD5bZcMivWxGzod8AWx6AjJTKFAlV6sw3e7IRwbw0lP4WsW65kRIInHEAagw7afU5iC47Ktw=,iv:8KPrxR42XPdCURZZvtsPJ52EUmwfb00cRxNX883Sqkc=,tag:j9rht4/EfqBihdgFEzQJRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
