# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:+/z77i2B816GH9wxqrZ0ahSbaqNRNNQ59i92V7jyDKkHbJnJSQ==,iv:evGqQamz9xNE/sW+RLQiBWY5miOrZ1FS0qdSu7bVX+E=,tag:w41nW/YCltVlBRSqFELa3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOXR6WlBpWSt4Y0J2ZFA3
            SUppU1JCRlovSzczcUowZ3lTdk4vYUMrYWc4CnRWWU11WTVjeGV6OE1zaVd3SURV
            cVV5STdhTW5XQ0k3RjhxNmJaamVGcjQKLS0tIHVxUzN3SzI5aFY5Q1plZmFCN042
            ZDdSMEU1R0JtRVJ3VXlGVEVlbHlUS1UKipHJabR+wfnL2e54W9CJqCsyAsIU4lE2
            qRn53NaxH7AR0zHdFlZkUkQ1KzZfz36Sh5MQNoqVLWU6/GwaXDYOdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-28T21:04:02Z"
    mac: ENC[AES256_GCM,data:fXPrf14RxmLjYBTC80S0LieLbFwAK23UTAS8k1Uz50udrnAqR7L9cbFfOG/1BOP9vh/p1NjVZAch4k1pS4Z52dXL1RIEe8TGHkfiiqx43ALOe996drfwVQHD2kNm13j8RQSTxLyabrUhG4DdjJH9lULPkndUtC5yVTzwmmTDsLs=,iv:ea6DzLgqawwA7AEfLsBHIBRzqtTC/HmcsV7hadHGIhs=,tag:1LNOb1Jc0PCsnfkG3zSZJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
