# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
data:
    #ENC[AES256_GCM,data:XYBe3QCQ9eVy3ivkpWxPp0MLN6bkMIhKT7pq0vav+IAkpmZaM7vFTvXEHIQFEMs1iHKxR4IaFqKN,iv:tm0vkHk3fg8lTeqlS2dLS8k9cFU9/9+/3/J6AzvYvjM=,tag:or77xgyuYtXWlEvk38vp6Q==,type:comment]
    #ENC[AES256_GCM,data:Q4JkKSyiOgl5ERwTWwO4bGQ9DjB05kwb3E6ZUh7b41Pxkk2/B9v3N1EN0YU46hQRmOMw+xHPhTUL,iv:pu80KRMSx+KGjEkidG8q18MicjJ2jFo64pmglZkT3Ag=,tag:skbMB6M+QAGYAO6UNtA7+w==,type:comment]
    api-token: ENC[AES256_GCM,data:jPxUfhHFg6YZhepWoloBRcdspe6O5v2mZdchzywuXOJFylz8qlvsgNGTd/74IRwnBu+5Oq4GcRg=,iv:Dpq2eBwVq4h/dG2a0Ju8KBsQb64bRi/CqmlgqAwouHQ=,tag:Mp1qBFZIkFTl/RzLmRT8hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ODR0RlI5b2tCQ1lHL01D
            bXRRUEllcXY2bVJRNTd4U0VuRGYxaS9ycEY4CkVzdXRmaHJtc01vcTJFSVhNc2FL
            NHFzY0srMGVRcWxWTHVKZEVtWmtTQlEKLS0tIHdzd1JoL0h3QStPTHQzbE9rc2JC
            R2tyRFBuaWhJTUcvai9kYmgvbTREL1EKnvxaTzIF/exn9g8yCfVlz7kzx3GMIRBO
            /gVClm6EAIm3UjdO/KB2xNiTffiXI9ex9nObKvP3Kob7g8hFnlrM/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-08T13:22:25Z"
    mac: ENC[AES256_GCM,data:tdBzLw5IJbvTr5ZlAQpGavj3ZV2ghUnms76FAj341MJTXXlV+zHP4Mf8oXAQjKA6IrNPlU1tcAWt3q7noTPB++AzqQEKQO+Ob7DmIfAY8plgw1O55t0DcbqIM8kFX5ZMVejLo/6FzyFJdGLwE3fqZAHqJkbZ/TzEpDugnHiVxOI=,iv:+DN/WiNVxEjy5YRcezlGfbUzRsTEHHz1aRYUHzc/E9Q=,tag:qThIsGSYTW3yJleA9PfEZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
