# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:jY3CapJfn/PDIfTYpgq2VTIq/MdSZIR47MXD2w56gi+p/r9RBQ==,iv:7mXVBDMXcIojMF17ZdCBr2Vk54Clj3Ps9NImlhqVpBE=,tag:/gixsKInIqurKvss35+/WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ODR0RlI5b2tCQ1lHL01D
            bXRRUEllcXY2bVJRNTd4U0VuRGYxaS9ycEY4CkVzdXRmaHJtc01vcTJFSVhNc2FL
            NHFzY0srMGVRcWxWTHVKZEVtWmtTQlEKLS0tIHdzd1JoL0h3QStPTHQzbE9rc2JC
            R2tyRFBuaWhJTUcvai9kYmgvbTREL1EKnvxaTzIF/exn9g8yCfVlz7kzx3GMIRBO
            /gVClm6EAIm3UjdO/KB2xNiTffiXI9ex9nObKvP3Kob7g8hFnlrM/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-08T13:16:01Z"
    mac: ENC[AES256_GCM,data:66162dezw2NfqtmIBYTWn5Bv+RLKYttKQzFDfgiAQL/47CFnVMzDb4VxBtmlD1wYhL5sP0fu7WZt5QoihJU+NcY2sBvWNX/lT1XtEfIHFvatTjadBWLXUZ0gdCDkQq9X/Nv0izCkm66FRB1Ao6bFG9Pj6z8qA0pM4ifSa3TSsf8=,iv:IARV2E6Ps1jgIgN9Ua7FMf1xATQG7ts9ODryAvj9Ba0=,tag:I+encJC0r/AKtPhKODKB/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
