---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app whisper
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  rollback:
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      whisper:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.6.4
              pullPolicy: IfNotPresent
            env:
              WHISPER__INSTANCE_NAME: Whisper
              WHISPER__PORT: &port 11434
              WHISPER__LOG_LEVEL: info
              TZ: ${TZ}
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_MODELS: &modelPath "/models"
              OLLAMA_KEEP_ALIVE: "24h"
              OLLAMA_LOAD_TIMEOUT: "600"
              OLLAMA_CONTEXT_LENGTH: "8192"
            resources:
              requests:
                memory: "256M"
              limits:
                memory: "8G"

    service:
      app:
        controller: *app
        ports:
          whisper:
            port: *port

    persistence:
      data:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
        - path: /root/.ollama
      models:
        enabled: true
        existingClaim: ollama-models
        advancedMounts:
          whisper:
            app:
            - path: *modelPath
