---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app whisper
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  rollback:
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      whisper:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: rhasspy/wyoming-whisper
              tag: latest
              pullPolicy: Always
            args:
            - --model
            - base
            - --language
            - en
            env:
              WHISPER__INSTANCE_NAME: Whisper
              WHISPER__PORT: &port 10300
              WHISPER__LOG_LEVEL: info
              ASR_MODEL: small # tiny, base, small, medium, large, large-v1, large-v2 and large-v3
              ASR_ENGINEL: faster_whisper # openai_whisper, faster_whisper
            resources:
              requests:
                memory: "256M"
              limits:
                memory: "8G"

    service:
      app:
        controller: *app
        ports:
          whisper:
            port: *port
            protocol: TCP

    persistence:
      data:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
