---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app whisper
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  rollback:
    recreate: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    controllers:
      whisper:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            # DO NOT ENABLE
            # Enabling this adds an extra default route to the container. My IoT network is locked down tight and results in failed external DNS lookups
            # k8s.v1.cni.cncf.io/networks: home-automation-iot-dhcp
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.10.100.14/24"],
                "mac": "aa:e9:02:a4:ee:41"
              }]

        containers:
          app:
            image:
              repository: onerahmet/openai-whisper-asr-webservice
              tag: v1.8.2@sha256:ce030954e4d0d6abad8f13e853b1c12745cc81f3e2ccef96d64fda927600f71a
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              WHISPER__INSTANCE_NAME: Whisper
              WHISPER__PORT: &port 9000
              WHISPER__APPLICATION_URL: &host "whisper.${INGRESS_DOMAIN}"
              WHISPER__LOG_LEVEL: info
              ASR_MODEL: small # tiny, base, small, medium, large, large-v1, large-v2 and large-v3
              ASR_ENGINEL: faster_whisper # openai_whisper, faster_whisper
            resources:
              requests:
                memory: "256M"
              limits:
                memory: "8G"

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
        - path: /root/.cache/whisper
    route:
      app:
        hostnames:
        - "{{ .Release.Name }}.${INGRESS_DOMAIN}"
        parentRefs:
        - name: internal
          namespace: kube-system
          sectionName: https
        rules:
        - backendRefs:
          - name: *app
            port: *port
