apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
stringData:
    smartthings_api_key: ENC[AES256_GCM,data:/quF02ziDY3gumOiK95bMAQApS/5Jp6k+MObVdRGPJ4oUg24,iv:zMOV9rO4zAHA0+OUn4wX3MSptG4uP4kKgT7uC7X6DL0=,tag:b0E57AVGWiJ32bhKKZtjVA==,type:str]
sops:
    age:
        - recipient: age1vx8dy8603amp9yuplkgvxaxu37y47d6myfw3urw55n7uazvqe9lsurpkxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVm5YNWxubHFNV2F1aVZk
            YVRqOUxJb2NPNmxDZVpFNWdab0tqUjU2dG5RCm5haU1LWVQ5T2xNdktidEZLRHNS
            ZXdHWXBBMWtMQ3ZITWpSTllrODJhSjgKLS0tIGlYNXdweHRtbkNNMVcrc2h4WlJC
            L2FsWCs3V0Rid3BmcnB1NEc4eU1najQKoZn8fP6Scx+b3e/JF817Kw2sltAW+Aan
            5RgpcSVsK580xjr4JdQmJOIKbtpKMnHBaGan4qNUruFbqZH1lq01IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-25T17:09:53Z"
    mac: ENC[AES256_GCM,data:nwAHBvrIaAlgsiysdFAaQq9ZTi/gOJYh32JdRSuRV9fszUvuyocI8Via4MYRzekrzz98gGJou0sDEkcqgnpzBkzQlMSQXWqSekexBZ72jFU4I19BeXAq37K/NsPv1Ibh/golS7bnob1DJ+J5UOe+7ra8BwqFPdb69mjifehLBDg=,iv:SeNzboKmhMjJ1qIwR0SinV6zJXkM9qEQQD+DGgwf+NM=,tag:31egZCS1rKpbAU6EguAYrQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
